config/routes.rb
Rails.application.routes.draw do
  resource :checksum, only: [:new, :create]

  root to: 'checksums#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checksums_controller.rb
class ChecksumsController < ApplicationController
  def new
    @checksum = Checksum.new
  end

  def create
    @checksum = Checksum.new checksum_params.fetch(:input, '')

    respond_to do |format|
      format.json
    end
  end

  private

  def checksum_params
    params.require(:checksum).permit(:input)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    title = [t('shared.name')]
    title.prepend @page_title if @page_title.present?
    return title.join(' &ndash; ').html_safe
  end

  def default_body_classes
    controller_path_array = controller_path.split('/')
    controller_path_array.append action_name
    controller_path_array.append Rails.env if Rails.env.test?
    controller_path_array.join(' ')
  end

  def svg_icon(path, name, options = {})
    width = options[:width].present? ? options[:width] : '16'
    height = options[:height].present? ? options[:height] : '16'
    css_class = options[:class].present? ? options[:class] : 'black'

    tag = "<svg width=\"#{width}px\" height=\"#{height}px\" viewBox=\"0 0 #{width} #{height}\" class=\"icon #{css_class}\">" +
          "<use xlink:href=\"#{ asset_path path }##{name}\"></use>" +
          "</svg>"

    tag.html_safe
  end

  def info_panel_tag(message, options = {})
    options[:container_only] = options[:container_only] || false

    if options[:class].present?
      options[:class] = ['info_panel', options[:class]].flatten.join(' ')
    else
      options[:class] = 'info_panel'
    end

    render partial: 'shared/info_panel', locals: { message: message, options: options }
  end

  def data_label(options = {}, &block)
    css_class = options[:class].present? ? "data_label #{options[:class]}" : 'data_label'
    data_label = tag.div capture(&block), class: 'data_label_text'
    if options[:icon].present?
      data_label_icon = svg_icon('icons.svg', options[:icon], class: options[:icon_class])
      data_label_icon = tag.div data_label_icon, class: 'data_label_icon'
      data_label = data_label_icon + data_label
    end
    options.merge! class: css_class
    tag.div data_label, options
  end

  def form_actions(inline: false, plain: false, centered: false, &block)
    css_class = %w(form_actions)
    css_class << 'inline' if inline
    css_class << 'plain' if plain
    css_class << 'centered' if centered
    css_class = css_class.join(' ')
    actions = tag.div capture(&block), class: 'inner'
    actions = tag.div actions, class: css_class
  end
end

app/views/checksums/_form.html.erb
<%= form_for checksum, url: checksum_path,
  remote: true, data: {
    type: :json,
    controller: 'checksum-form',
    action: 'ajax:success->checksum-form#showOutput',
    checksum_form_empty_output: checksum.output
  } do |f| %>
  <div class="form_field compact inline">
    <div class="field_label right">
      <%= f.label :input %>
    </div>
    <div class="field_input">
      <%= svg_icon('icons.svg', 'doc_text', class: 'field_icon') %>
      <%= f.text_field :input %>
    </div>
  </div>

  <%= info_panel_tag t('checksum.messages.rules').html_safe, class: 'inline text_only' %>

  <div class="form_field compact inline">
    <div class="field_label right">
      <%= label_tag nil, t('helpers.label.checksum.output') %>
    </div>
    <div class="field_input">
      <%= data_label do %>
        <span class="checksum_output" data-target="checksum-form.output">
          <%= checksum.output %>
        </span>
      <% end %>
    </div>
  </div>

  <%= form_actions inline: true do %>
    <%= f.submit t('checksum.actions.create'), class: 'button' %>
  <% end %>
<% end %>

app/views/checksums/new.html.erb
<div class="grid">
  <div class="unit centered checksum_form">
    <div class="panel">
      <h2><%= t('checksum.titles.new') %></h2>

      <%= render 'form', checksum: @checksum %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,user-scalable=no" />
    <meta name="turbolinks-cache-control" content="no-cache">
  </head>

  <%= tag.body class: default_body_classes do %>
    <main class="content">
      <%= yield %>
    </main>
  <% end %>
</html>

app/views/shared/_info_panel.html.erb
<%= tag.div options do %>
  <% if options[:class].include? 'text_only' %>
    <div class="info_icon">
      <%= svg_icon('icons.svg', (options[:icon] || 'info_circle')) %>
    </div>
  <% end %>

  <div class="info_panel_body">
    <% if options[:container_only] == true %>
      <%= message %>
    <% else %>
      <p class="info_panel_message"><%= message %></p>
    <% end %>
  </div>
<% end %>